<?php
session_start();
require_once 'config/database.php';
require_once 'includes/functions.php';
if (isLoggedIn()) { header('Location: customer/booking.php'); exit(); }
$error=''; $success='';
if ($_SERVER['REQUEST_METHOD']==='POST') {
 $first=trim($_POST['first_name']??''); $last=trim($_POST['last_name']??''); $age=(int)($_POST['age']??0); $phone=trim($_POST['phone']??''); $email=trim($_POST['email']??''); $password=$_POST['password']??''; $confirm=$_POST['confirm_password']??'';
 if ($first===''||$last===''||$age<1||$age>120||!isValidPhone($phone)||!isValidEmail($email)||strlen($password)<8||$password!==$confirm) $error='Please complete all fields correctly. Password must be at least 8 characters and both passwords must match.';
 else {
  $check=$conn->prepare('SELECT id FROM users WHERE email=? LIMIT 1'); $check->bind_param('s',$email); $check->execute();
  if($check->get_result()->num_rows) $error='An account with this email already exists.'; else {
   $username=strtolower(preg_replace('/[^a-z0-9]/i','', $first.'.'.$last)); if($username==='') $username='passenger'; $base=$username; $n=1;
   while(true){$q=$conn->prepare('SELECT id FROM users WHERE username=? LIMIT 1');$q->bind_param('s',$username);$q->execute();if(!$q->get_result()->num_rows)break;$username=$base.$n++;}
   $code=(string)random_int(100000,999999); $hash=password_hash($code,PASSWORD_DEFAULT); $expires=date('Y-m-d H:i:s',time()+900); $full=$first.' '.$last; $pw=hashPassword($password);
   $stmt=$conn->prepare('INSERT INTO users(username,email,password,role,full_name,first_name,last_name,age,phone,email_verified,verification_code_hash,verification_expires) VALUES(?,?,?,?,?,?,?,?,?,0,?,?)'); $role='CUSTOMER'; $stmt->bind_param('ssssssiisss',$username,$email,$pw,$role,$full,$first,$last,$age,$phone,$hash,$expires);
   if($stmt->execute()) { $subject='SafeWay email verification code'; $message='<div style="font-family:Arial,sans-serif"><h2>Welcome to SafeWay Transport</h2><p>Your verification code is:</p><h1 style="letter-spacing:6px">'.$code.'</h1><p>This code expires in 15 minutes.</p><p>If you did not create this account, ignore this email.</p></div>'; if(sendEmail($email,$subject,$message)) { $_SESSION['pending_verification_email']=$email; header('Location: verify-email.php'); exit(); } $conn->query('DELETE FROM users WHERE id='.(int)$conn->insert_id); $error='Account could not be created because the verification email could not be sent. Please try again.'; }
   else $error='Registration failed. Please try again.';
  }
 }
}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Passenger registration | SafeWay</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><link rel="stylesheet" href="assets/css/style.css"><link rel="stylesheet" href="assets/css/modern.css"></head><body><main class="auth-container py-4"><div class="container"><div class="auth-box mx-auto" style="max-width:760px"><div class="text-center mb-4"><div class="feature-icon mx-auto mb-3"><i class="fas fa-user-plus"></i></div><h2>Create passenger account</h2><p>Register with your email and verify it before booking.</p></div><?php if($error):?><div class="alert alert-danger"><?php echo htmlspecialchars($error);?></div><?php endif;?><form method="post" class="row g-3" novalidate><div class="col-md-6"><label class="form-label">First name</label><input class="form-control" name="first_name" required></div><div class="col-md-6"><label class="form-label">Last name</label><input class="form-control" name="last_name" required></div><div class="col-md-4"><label class="form-label">Age</label><input class="form-control" type="number" min="1" max="120" name="age" required></div><div class="col-md-8"><label class="form-label">Phone</label><input class="form-control" name="phone" placeholder="09xxxxxxxx" required></div><div class="col-12"><label class="form-label">Email</label><input class="form-control" type="email" name="email" required></div><div class="col-md-6"><label class="form-label">Password</label><input class="form-control" type="password" name="password" minlength="8" required></div><div class="col-md-6"><label class="form-label">Confirm password</label><input class="form-control" type="password" name="confirm_password" minlength="8" required></div><div class="col-12"><button class="btn btn-primary w-100 btn-lg" type="submit"><i class="fas fa-envelope-circle-check me-2"></i>Create account & send code</button></div></form><div class="text-center mt-4">Already registered? <a href="login.php">Sign in</a></div></div></div></main></body></html>