<?php
session_start(); require_once 'config/database.php'; require_once 'includes/functions.php';
$email=$_SESSION['pending_verification_email']??''; if(!$email){header('Location: register.php');exit();}
$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 $code=preg_replace('/\D/','',$_POST['code']??''); $stmt=$conn->prepare('SELECT id,verification_code_hash,verification_expires,status FROM users WHERE email=? AND role="CUSTOMER" LIMIT 1');$stmt->bind_param('s',$email);$stmt->execute();$u=$stmt->get_result()->fetch_assoc();
 if(!$u || $u['status']!=='active') $error='Account not found.'; elseif(!$u['verification_expires'] || strtotime($u['verification_expires'])<time()) $error='This code has expired. Please register again.'; elseif(!password_verify($code,$u['verification_code_hash'])) $error='Invalid verification code.'; else { $up=$conn->prepare('UPDATE users SET email_verified=1,verification_code_hash=NULL,verification_expires=NULL WHERE id=?');$up->bind_param('i',$u['id']);$up->execute();unset($_SESSION['pending_verification_email']);$success=true; }
}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Verify email | SafeWay</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="assets/css/style.css"><link rel="stylesheet" href="assets/css/modern.css"></head><body><main class="auth-container"><div class="auth-box mx-auto text-center" style="max-width:520px"><div class="feature-icon mx-auto mb-3"><i class="fas fa-shield-check"></i></div><?php if(!empty($success)):?><h2>Email verified!</h2><p>Your passenger account is ready. You can now sign in and book your bus.</p><a class="btn btn-primary w-100" href="login.php">Continue to sign in</a><?php else:?><h2>Verify your email</h2><p>We sent a 6-digit verification code to <strong><?php echo htmlspecialchars($email);?></strong>.</p><?php if($error):?><div class="alert alert-danger"><?php echo htmlspecialchars($error);?></div><?php endif;?><form method="post"><input class="form-control form-control-lg text-center mb-3" name="code" inputmode="numeric" maxlength="6" placeholder="000000" required><button class="btn btn-primary w-100" type="submit">Verify email</button></form><div class="mt-3"><a href="register.php">Back to registration</a></div><?php endif;?></div></main></body></html>